### ISSUE TITLE
Remove filter methods' "is:" prefix

### ISSUE THREAD

**Issue by NatashaKSS** [cs2103aug2015-w13-2j/main#140]
We are also (as discussed on 29/10 after the CS2101 Software Demo Conference), not going to support filtering the 'inverse' of the "archived", "important" and "done" tasks, as these are unnecessary.

**Comment by chunqi** [comment]
@NatashaKSS important by itself will result in the Parser recognizing it as a reserved keyword instead hmm
Oct 30, 2015 11:59:15 PM sg.edu.cs2103aug2015_w13_2j.parser.Parser parseCommand
INFO: [RESERVED=filter][RESERVED=important]
