### ISSUE TITLE
Undo/Redo doesn't work properly across different filter displays

### ISSUE THREAD

**Issue by luyangkenneth** [cs2103aug2015-w13-2j/main#154]
- Error reconstruction:
  Search for something
  Delete one of the tasks
  Pop filter
  Try undo/redo several times
- Result:
  Task-modifying command cannot be undone
- Maybe dissociate filters from the undo/redo stack entirely?

**Comment by NatashaKSS** [comment]
Yup, I mis-spelt a word in the code whilst documenting certain parts of Logic!
The Undo/Redo works across filters (tried for delete and edit commands)
But I've found that another main problem lies in the Search function (task-modifying features don't work within that environment), which Chunqi has just messaged me that he's fixing now!
- This Search function problem has its bug issues reported too on GitHub
