### ISSUE TITLE
I want to filter the tasks to show only those on a particular date or within a specified range

### ISSUE THREAD

**Issue by chunqi** [cs2103aug2015-w13-2j/main#19]
so that I can plan my schedule in advance

**Comment by luyangkenneth** [comment]
@chunqi is this already implemented / do we need this?

**Comment by chunqi** [comment]
@luyangkenneth not yet this is WIP

**Comment by luyangkenneth** [comment]
@chunqi okay! but actually this one not very important luh

**Comment by luyangkenneth** [comment]
Not implementing this.
