### ISSUE TITLE
Create Parser class and ParserTest class

### ISSUE THREAD

**Issue by NatashaKSS** [cs2103aug2015-w13-2j/main#34]

**Comment by chunqi** [comment]
- The Parser component is to be instantiated once and used repeatedly, but the constructor requires a String argument.
- Your usage of split regex will result in blank tokens if the user enters something such as "add  something" with 2 spaces in between. Use "\\s+" to match one or more whitespaces.
- You should update your interface to match your implementation whenever you change the component class.

For the parser state machine may I suggest the following to improve the readability and reduce the number of methods needed:
1. Have enumerated parser states such as TASK_NAME and TASK_FLAG for example
2. Check for all of them into a giant switch statement
3. Process the command char by char until some end marker of sorts

Example:

``` java
switch(mState) {
  //... Example state
  case State.TASK_NAME:
    StringBuilder sb = new StringBuilder();
    while(true) {
        char c = getNextChar();
        if(c == '"') {
          // End of name reached
          task.setName(sb.toString());
          // Or if you want to keep internal parse structure
          mTokens.add(Token.NAME(sb.toString()));
          // Transisiton to another state
          mState = State.GENERAL
        } else {
          sb.append(c);
        }
    }
    break;
}
```
