### ISSUE TITLE
Data file uses vertical pipe | as delimiter between labels

### ISSUE THREAD

**Issue by luyangkenneth** [cs2103aug2015-w13-2j/main#58]
This means that the user cannot include the pipe symbol in the task name, or else problems will arise when parseTask() is called.

**Comment by luyangkenneth** [comment]
We could block the user from using pipe symbols in the task names (Logic), or reject all inputs entirely if they contain the pipe symbols (Parser).

How do you guys suggest we resolve this, and under which component?

**Comment by chunqi** [comment]
Why not use a symbol that is programatically easy to check for such as \0 (null terminator) but is difficult for user to enter during normal use?

**Comment by luyangkenneth** [comment]
I thought of using special ascii symbols too but I realised that the text file has to remain user-readable / editable. So ideally there exists such a character that is difficult to enter normally but can also serve as a separator symbol.

**Comment by luyangkenneth** [comment]
Suggested solution that I will be working on:
1. Separate attributes by a newline and tasks by an additional newline
2. Escaping special characters (e.g. \n) in user-input
