### ISSUE TITLE
NEWLINE char in TextUI class keyPressed method causes single commands to be parsed as ALAPHA_NUM

### ISSUE THREAD

**Issue by NatashaKSS** [cs2103aug2015-w13-2j/main#79]
E.g. When 'list' command is input in the text box, the token "list" is detected as an ALPHA_NUM instead of RESERVED
For some reason, only for single token commands, this bug appears.

**Comment by NatashaKSS** [comment]
@SmokinClove Yup, everything works as normally with that. But question is ....the NEWLINE char could be important!

Will keep this issue open first!

**Comment by chunqi** [comment]
That NEWLINE is indeed not needed. It was originally there when the echo command called print on the TextUI and the NEWLINE thus had to be injected manually.
